CREATE TABLE LINK (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	redirect_to TEXT NOT NULL,
	code VARCHAR(10) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    created_by UUID NOT NULL REFERENCES USERS(ID)
);